name: era_jaya_inventory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.0
  get: 4.6.5
  firebase_core: 1.18.0
  cloud_firestore: 3.1.18
  google_fonts: 3.0.1
  splash_screen_view: ^3.0.0
  dot_navigation_bar: ^1.0.1+4
  dropdown_button2: ^1.6.3
  intl: ^0.17.0
  pdf: ^3.8.1
  datetime_picker_formfield: ^2.0.0
  # dropdown_search: ^5.0.2  
  # flutter_native_splash: ^2.2.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

splash_screen_view:
  color: "#ffffff"